-- SMARTSCHOOL SENTINEL - COMPLETE DATABASE SCHEMA
-- This is the complete, production-ready database schema
-- Run migrations in order: 005-add-anomaly-system.sql, then 006-add-gate-system.sql

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE public.absence_reasons (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  student_id text NOT NULL,
  student_name text NOT NULL,
  absence_date date NOT NULL,
  absence_type text NOT NULL,
  reason_details text,
  supporting_document_url text,
  document_type text,
  submitted_by text NOT NULL,
  submitted_at timestamp with time zone DEFAULT now(),
  approval_status text DEFAULT 'pending'::text,
  approved_by text,
  approved_at timestamp with time zone,
  rejection_reason text,
  is_multi_day boolean DEFAULT false,
  end_date date,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT absence_reasons_pkey PRIMARY KEY (id),
  CONSTRAINT absence_reasons_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.user_registry(user_id)
);
CREATE TABLE public.academic_calendar (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  date date NOT NULL UNIQUE,
  day_type text NOT NULL CHECK (day_type = ANY (ARRAY['regular'::text, 'half_day'::text, 'holiday'::text, 'exam_day'::text, 'special_event'::text])),
  event_name text,
  event_description text,
  modified_schedule jsonb,
  active_timetable_template text,
  is_school_day boolean DEFAULT true,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT academic_calendar_pkey PRIMARY KEY (id)
);
CREATE TABLE public.attendance_logs (
  id bigint NOT NULL DEFAULT nextval('attendance_logs_id_seq'::regclass),
  user_id text NOT NULL,
  user_name text NOT NULL,
  person_type text NOT NULL CHECK (person_type = ANY (ARRAY['student'::text, 'teacher'::text, 'staff'::text, 'visitor'::text])),
  event_type text NOT NULL CHECK (event_type = ANY (ARRAY['breakfast'::text, 'lunch'::text, 'supper'::text, 'class'::text, 'morning_roll_call'::text, 'evening_roll_call'::text, 'entry'::text, 'exit'::text])),
  period_number integer,
  subject text,
  camera_id text NOT NULL,
  camera_name text NOT NULL,
  camera_group text,
  timestamp timestamp with time zone NOT NULL,
  log_date date,
  attendance_status text DEFAULT 'present'::text CHECK (attendance_status = ANY (ARRAY['present'::text, 'on_time'::text, 'late_minor'::text, 'late_major'::text, 'very_late'::text, 'absent'::text])),
  confidence_score double precision CHECK (confidence_score >= 0::double precision AND confidence_score <= 100::double precision),
  capture_image_url text,
  raw_payload jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT attendance_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.camera_logs (
  id bigint NOT NULL DEFAULT nextval('camera_logs_id_seq'::regclass),
  topic text NOT NULL,
  device_id text NOT NULL,
  raw_payload jsonb NOT NULL,
  operator text,
  person_id text,
  person_name text,
  record_id text,
  verify_status text,
  similarity double precision,
  detection_time timestamp with time zone,
  processed boolean DEFAULT false,
  processed_at timestamp with time zone,
  processing_error text,
  received_at timestamp with time zone DEFAULT now(),
  CONSTRAINT camera_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.camera_metadata (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  device_id text NOT NULL UNIQUE,
  display_name text NOT NULL,
  device_serial text,
  ip_address inet,
  rtsp_url text,
  location_tag text NOT NULL,
  building text,
  floor text,
  area_description text,
  camera_group text,
  backup_camera_ids ARRAY,
  coverage_overlaps_with ARRAY,
  arming_schedule jsonb,
  detection_sensitivity double precision DEFAULT 0.85,
  deduplication_window_seconds integer DEFAULT 60,
  is_active boolean DEFAULT true,
  is_online boolean DEFAULT false,
  last_heartbeat timestamp with time zone,
  last_detection timestamp with time zone,
  total_detections_today integer DEFAULT 0,
  uptime_percentage double precision,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT camera_metadata_pkey PRIMARY KEY (id)
);
CREATE TABLE public.class_schedule (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  class_id text NOT NULL,
  grade text NOT NULL,
  timetable_template_id uuid,
  period_number integer NOT NULL,
  day_of_week integer NOT NULL,
  subject text NOT NULL,
  teacher_id text,
  classroom_location text NOT NULL,
  building text,
  room_number text,
  camera_ids ARRAY NOT NULL,
  primary_camera_id text,
  expected_student_ids ARRAY NOT NULL,
  expected_count integer NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT class_schedule_pkey PRIMARY KEY (id),
  CONSTRAINT class_schedule_timetable_template_id_fkey FOREIGN KEY (timetable_template_id) REFERENCES public.timetable_template(id),
  CONSTRAINT class_schedule_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.user_registry(user_id)
);
CREATE TABLE public.flagged_students (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  student_id text NOT NULL,
  student_name text NOT NULL,
  class text NOT NULL,
  flag_type text NOT NULL,
  severity text NOT NULL,
  description text NOT NULL,
  absence_count integer,
  absence_rate double precision,
  pattern_description text,
  intervention_required boolean DEFAULT true,
  intervention_status text DEFAULT 'pending'::text,
  assigned_to text,
  flagged_at timestamp with time zone DEFAULT now(),
  resolved_at timestamp with time zone,
  resolution_notes text,
  created_by text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT flagged_students_pkey PRIMARY KEY (id),
  CONSTRAINT flagged_students_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.user_registry(user_id)
);
CREATE TABLE public.intervention_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  student_id text NOT NULL,
  flagged_student_id uuid,
  intervention_type text NOT NULL,
  intervention_date date NOT NULL,
  conducted_by text NOT NULL,
  notes text NOT NULL,
  action_items ARRAY,
  follow_up_required boolean DEFAULT false,
  follow_up_date date,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT intervention_logs_pkey PRIMARY KEY (id),
  CONSTRAINT intervention_logs_flagged_student_id_fkey FOREIGN KEY (flagged_student_id) REFERENCES public.flagged_students(id),
  CONSTRAINT intervention_logs_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.user_registry(user_id)
);
CREATE TABLE public.notification_queue (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  recipient_id text NOT NULL,
  recipient_type text NOT NULL,
  recipient_contact text NOT NULL,
  notification_type text NOT NULL,
  priority text DEFAULT 'normal'::text,
  subject text NOT NULL,
  message text NOT NULL,
  delivery_method text NOT NULL,
  status text DEFAULT 'pending'::text,
  sent_at timestamp with time zone,
  delivered_at timestamp with time zone,
  read_at timestamp with time zone,
  retry_count integer DEFAULT 0,
  max_retries integer DEFAULT 3,
  last_error text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notification_queue_pkey PRIMARY KEY (id)
);
CREATE TABLE public.schedule_overrides (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  date date NOT NULL,
  affected_classes ARRAY,
  affected_periods ARRAY,
  affected_grades ARRAY,
  override_type text NOT NULL,
  reason text NOT NULL,
  new_location text,
  new_camera_ids ARRAY,
  new_start_time time without time zone,
  new_end_time time without time zone,
  new_teacher_id text,
  substitute_teacher_id text,
  created_by text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT schedule_overrides_pkey PRIMARY KEY (id)
);
CREATE TABLE public.special_events (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  event_name text NOT NULL,
  event_type text NOT NULL,
  event_category text,
  event_location text NOT NULL,
  is_offsite boolean DEFAULT false,
  start_datetime timestamp with time zone NOT NULL,
  end_datetime timestamp with time zone NOT NULL,
  all_day_event boolean DEFAULT false,
  participant_ids ARRAY NOT NULL,
  participant_count integer NOT NULL,
  supervising_teacher_ids ARRAY,
  affected_periods ARRAY,
  replaces_regular_classes boolean DEFAULT true,
  requires_exit_tracking boolean DEFAULT false,
  requires_return_tracking boolean DEFAULT false,
  expected_departure_time timestamp with time zone,
  expected_return_time timestamp with time zone,
  status text DEFAULT 'scheduled'::text,
  departure_confirmed_at timestamp with time zone,
  departure_confirmed_count integer DEFAULT 0,
  return_confirmed_at timestamp with time zone,
  return_confirmed_count integer DEFAULT 0,
  notes text,
  created_by text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT special_events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.student_movements (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  student_id text NOT NULL,
  student_name text NOT NULL,
  movement_type text NOT NULL,
  timestamp timestamp with time zone NOT NULL,
  camera_id text NOT NULL,
  camera_name text NOT NULL,
  exit_reason text,
  authorized_by text,
  authorization_method text,
  expected_return_time timestamp with time zone,
  related_exit_id uuid,
  actual_return_time timestamp with time zone,
  return_confirmed boolean DEFAULT false,
  late_return boolean DEFAULT false,
  late_return_minutes integer,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT student_movements_pkey PRIMARY KEY (id),
  CONSTRAINT student_movements_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.user_registry(user_id)
);
CREATE TABLE public.student_whereabouts (
  user_id text NOT NULL,
  user_name text NOT NULL,
  current_location text,
  current_location_type text,
  arrived_at timestamp with time zone NOT NULL,
  expected_location text,
  expected_location_type text,
  expected_until timestamp with time zone,
  location_match boolean,
  discrepancy_duration integer,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT student_whereabouts_pkey PRIMARY KEY (user_id)
);
CREATE TABLE public.system_logs (
  id bigint NOT NULL DEFAULT nextval('system_logs_id_seq'::regclass),
  log_type text NOT NULL,
  log_category text,
  message text NOT NULL,
  metadata jsonb,
  severity text DEFAULT 'info'::text,
  user_id text,
  camera_id text,
  ip_address inet,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT system_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.timetable_template (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  template_name text NOT NULL,
  description text,
  day_of_week integer NOT NULL CHECK (day_of_week >= 1 AND day_of_week <= 7),
  period_number integer NOT NULL,
  period_name text NOT NULL,
  period_type text NOT NULL CHECK (period_type = ANY (ARRAY['class'::text, 'assembly'::text, 'break'::text, 'lunch'::text, 'roll_call'::text])),
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  is_attendance_period boolean DEFAULT true,
  attendance_grace_minutes integer DEFAULT 5,
  late_threshold_major integer DEFAULT 15,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT timetable_template_pkey PRIMARY KEY (id)
);
CREATE TABLE public.tracking_notes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id text NOT NULL,
  user_name text NOT NULL,
  note_type text DEFAULT 'general'::text,
  note_text text NOT NULL,
  related_date date DEFAULT CURRENT_DATE,
  related_period integer,
  related_event_id uuid,
  created_by text NOT NULL,
  created_by_role text,
  is_private boolean DEFAULT false,
  visible_to_roles ARRAY,
  timestamp timestamp with time zone DEFAULT now(),
  CONSTRAINT tracking_notes_pkey PRIMARY KEY (id),
  CONSTRAINT tracking_notes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_registry(user_id)
);
CREATE TABLE public.user_registry (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id text NOT NULL UNIQUE,
  full_name text NOT NULL,
  person_type text NOT NULL CHECK (person_type = ANY (ARRAY['student'::text, 'teacher'::text, 'staff'::text, 'visitor'::text])),
  grade text,
  class text,
  stream text,
  house text,
  parent_phone text,
  parent_email text,
  employee_id text,
  department text,
  photo_url text,
  face_descriptor jsonb,
  current_status text DEFAULT 'unknown'::text,
  status_reason text,
  expected_return timestamp with time zone,
  last_seen_camera text,
  last_seen_time timestamp with time zone,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_registry_pkey PRIMARY KEY (id)
);